"""Evaluate NuosuGPT CSV outputs on Yi OCR, translation, and dialogue."""

import argparse
import json
import math
from collections import Counter
from pathlib import Path

import pandas as pd


def normalize(value):
    return "" if value is None or (isinstance(value, float) and pd.isna(value)) else "".join(str(value).strip().split())


def edit_distance(reference, hypothesis):
    previous = list(range(len(hypothesis) + 1))
    for i, char in enumerate(reference, 1):
        current = [i]
        for j, other in enumerate(hypothesis, 1):
            current.append(min(previous[j] + 1, current[j - 1] + 1, previous[j - 1] + (char != other)))
        previous = current
    return previous[-1]


def cer(reference, hypothesis):
    reference, hypothesis = normalize(reference), normalize(hypothesis)
    return 0.0 if not reference and not hypothesis else (100.0 if not reference else 100.0 * edit_distance(reference, hypothesis) / len(reference))


def ngrams(text, n):
    return Counter(tuple(text[i:i + n]) for i in range(len(text) - n + 1))


def bleu4(references, hypotheses):
    clipped, totals, ref_length, hyp_length = [0] * 4, [0] * 4, 0, 0
    for reference, hypothesis in zip(references, hypotheses):
        reference, hypothesis = list(normalize(reference)), list(normalize(hypothesis))
        ref_length += len(reference)
        hyp_length += len(hypothesis)
        for n in range(1, 5):
            ref_counts, hyp_counts = ngrams(reference, n), ngrams(hypothesis, n)
            totals[n - 1] += sum(hyp_counts.values())
            clipped[n - 1] += sum(min(count, ref_counts[key]) for key, count in hyp_counts.items())
    precision = [clipped[i] / totals[i] if totals[i] else 0.0 for i in range(4)]
    if not hyp_length or min(precision) == 0:
        return 0.0
    bp = 1.0 if hyp_length > ref_length else math.exp(1 - ref_length / hyp_length)
    return 100.0 * bp * math.exp(sum(math.log(value) for value in precision) / 4)


def rouge_l(reference, hypothesis):
    reference, hypothesis = list(normalize(reference)), list(normalize(hypothesis))
    if not reference or not hypothesis:
        return 0.0
    previous = [0] * (len(hypothesis) + 1)
    for char in reference:
        current = [0]
        for j, other in enumerate(hypothesis, 1):
            current.append(previous[j - 1] + 1 if char == other else max(previous[j], current[j - 1]))
        previous = current
    precision, recall = previous[-1] / len(hypothesis), previous[-1] / len(reference)
    return 2 * precision * recall / (precision + recall) if precision + recall else 0.0


def main():
    parser = argparse.ArgumentParser(description="Evaluate NuosuGPT task outputs.")
    parser.add_argument("csv", type=Path, help="CSV generated by run_nuosugpt_inference.py")
    parser.add_argument("--answer-column", default="Model_Answer")
    parser.add_argument("--task-counts", default="303,305,283")
    parser.add_argument("--output-dir", type=Path, default=Path("metrics_output"))
    args = parser.parse_args()
    counts = tuple(int(value) for value in args.task_counts.split(","))
    if len(counts) != 3:
        raise ValueError("--task-counts must be OCR,translation,dialogue")
    frame = None
    for encoding in ("utf-8-sig", "utf-8", "gb18030"):
        try:
            frame = pd.read_csv(args.csv, encoding=encoding)
            break
        except UnicodeDecodeError:
            continue
    if frame is None:
        raise UnicodeError(f"Unable to decode CSV: {args.csv}")
    if len(frame) != sum(counts) or "Target" not in frame or args.answer_column not in frame:
        raise ValueError("CSV rows, Target, or answer column do not match the specified evaluation split")
    ocr_end, translation_end = counts[0], counts[0] + counts[1]
    frame["Eval_Task"] = ["ocr" if i < ocr_end else "translation" if i < translation_end else "dialogue" for i in range(len(frame))]
    frame["Exact_Match"] = [int(normalize(ref) == normalize(hyp)) for ref, hyp in zip(frame.Target, frame[args.answer_column])]
    frame["CER"] = [cer(ref, hyp) for ref, hyp in zip(frame.Target, frame[args.answer_column])]
    frame["ROUGE_L_F1"] = [rouge_l(ref, hyp) if task == "dialogue" else 0.0 for task, ref, hyp in zip(frame.Eval_Task, frame.Target, frame[args.answer_column])]
    ocr, translation, dialogue = (frame.iloc[:ocr_end], frame.iloc[ocr_end:translation_end], frame.iloc[translation_end:])
    summary = {
        "total_samples": len(frame), "ocr_samples": len(ocr), "translation_samples": len(translation), "dialogue_samples": len(dialogue),
        "ocr_exact_accuracy": round(100 * ocr.Exact_Match.mean(), 2), "ocr_cer": round(ocr.CER.mean(), 2),
        "translation_bleu4": round(bleu4(translation.Target, translation[args.answer_column]), 2), "translation_exact_accuracy": round(100 * translation.Exact_Match.mean(), 2), "translation_cer": round(translation.CER.mean(), 2),
        "dialogue_rouge_l": round(100 * dialogue.ROUGE_L_F1.mean(), 2), "dialogue_cer": round(dialogue.CER.mean(), 2),
    }
    args.output_dir.mkdir(parents=True, exist_ok=True)
    frame.to_csv(args.output_dir / "per_sample_metrics.csv", index=False, encoding="utf-8-sig")
    (args.output_dir / "metrics_summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
